### ISSUE TITLE
UI Change

### ISSUE THREAD

**Issue by TartejBrothers** [CorgiDev/CorgiDevSite#154]
I think there is no need for a whole span row for home button, as there is home button in the navbar, it should not be made in a separate row below that. 

The bottom footer on hover, makes a border around the whole footer instead of the image.

**Comment by CorgiDev** [comment]
@TartejBrothers do you mean the navigation breadcrumb row on the home page?

**Comment by TartejBrothers** [comment]
I meant this row 
![image](https://github.com/CorgiDev/CorgiDevSite/assets/112921727/e51af368-33d8-4186-9e12-8817307e7a37)

The row can be used for something else, only home which is already present on top doesn't utilise it well.

**Comment by CorgiDev** [comment]
@TartejBrothers I am going to merge in the fixes now. I think it will close this issue automatically once I merge it in, but feel free to follow-up if you notice the issues don't appear to be resolved. Thanks again for your feedback.
